#! /usr/bin/env python3
"Lint one or more of my projects"
import argparse
from lint_core import lint_all

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('-p', '--project', nargs='+')
lint_all(parser.parse_args())
