#! /usr/bin/env python3
"Another linter frontend"
import argparse
from lint_core import Main

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('-l', '--linter', choices=['pylint', 'flake8'], required=True)
parser.add_argument('-r', '--recursive', action='store_true')
parser.add_argument('-f', '--file')
Main(parser.parse_args())
